apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: '{{.Values.appName}}'
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /{{.Values.microservices.myservice.serviceName}}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: '{{.Values.microservices.myservice.serviceName}}'
            port:
              name: http
